// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtz1k-J9Yq2e6C5keJTyUams_XlggBcI',
    appId: '1:502470215529:web:b8f8ae0fa695e828ca9ff8',
    messagingSenderId: '502470215529',
    projectId: 'cooffeeshop-flutter-academy',
    authDomain: 'coffee-shop-flutter.firebaseapp.com',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD05NQTa24OElt7xbSyzK3AsF1qCXgH5eg',
    appId: '1:682223097542:android:6608623c36e3caf0dda9c7',
    messagingSenderId: '682223097542',
    projectId: 'cooffeeshop-flutter-academy',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05NQTa24OElt7xbSyzK3AsF1qCXgH5eg',
    appId: '1:682223097542:android:6608623c36e3caf0dda9c7',
    messagingSenderId: '682223097542',
    projectId: 'cooffeeshop-flutter-academy',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05NQTa24OElt7xbSyzK3AsF1qCXgH5eg',
    appId: '1:682223097542:android:6608623c36e3caf0dda9c7',
    messagingSenderId: '682223097542',
    projectId: 'cooffeeshop-flutter-academy',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD05NQTa24OElt7xbSyzK3AsF1qCXgH5eg',
    appId: '1:682223097542:android:6608623c36e3caf0dda9c7',
    messagingSenderId: '682223097542',
    projectId: 'cooffeeshop-flutter-academy',
    authDomain: 'coffee-shop-flutter.firebaseapp.com',
    storageBucket: 'cooffeeshop-flutter-academy.appspot.com',
  );
}
